drivers: touchscreen: st: Fix error cause a function declaration is deprecated
clang 15.0 warns:

../drivers/input/touchscreen/st/fts_lib/ftsIO.c:85:22: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
struct device *getDev()
                     ^
                      void
../drivers/input/touchscreen/st/fts_lib/ftsIO.c:93:29: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
struct i2c_client *getClient()
                            ^
                             void
2 errors generated.

../drivers/input/touchscreen/st/fts_lib/ftsTime.c:95:16: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
char *timestamp()
               ^
                void
1 error generated.

Change-Id: If92e4daf0a44e911f958048f0a7d06f857bfc6d4
Signed-off-by: fadlyas07 <mhmmdfdlyas@gmail.com>
Signed-off-by: pix106 <sbordenave@gmail.com>